# Generated by Django 4.0.3 on 2022-08-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome',
            new_name='nome_pessoa',
        ),
    ]
