# Generated by Django 4.1 on 2022-08-10 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0008_receita_foto_receita_alter_receita_data_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 19, 45, 59, 706400)),
        ),
    ]
